[Unit]
After=zaigr-runtime-setup.service
Requires=zaigr-runtime-setup.service
Before=zaigr-boot-hooks.service ssh.service

[Service]
ExecStartPre=/usr/bin/truncate -s 0 /var/log/opensnitchd.log
ExecStart=
ExecStart=/usr/bin/opensnitchd -debug -log-file /var/log/opensnitchd.log -rules-path /etc/opensnitchd/rules -process-monitor-method proc
ExecStartPost=/usr/local/lib/zaigr/wait-opensnitch
RestartSec=1s
